<?php

namespace Database\Seeders;

use App\Models\GameMatch;
use App\Models\Skin;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Create Catalog of 32 Combat Tank Chassis
        $skins = [
            // --- COMMON TIER ---
            [
                'name' => 'Neon Vanguard',
                'slug' => 'neon-vanguard',
                'type' => 'assault',
                'rarity' => 'common',
                'price_coins' => 0,
                'price_gems' => 0,
                'color_primary' => '#00f0ff',
                'color_secondary' => '#ff007f',
                'color_glow' => '#00f0ff',
                'bullet_color' => '#00f0ff',
                'description' => 'Standard issue cyber-tank chassis equipped with pulse ion reactor and neon trim.',
                'stats' => ['speed' => 1.0, 'fire_rate' => 1.0, 'damage' => 1.0, 'max_hp' => 100, 'shield' => 50, 'bullet_speed' => 1.0, 'special_perk' => 'Ion Pulse Core'],
                'is_default' => true,
            ],
            [
                'name' => 'Iron Behemoth',
                'slug' => 'iron-behemoth',
                'type' => 'heavy',
                'rarity' => 'common',
                'price_coins' => 200,
                'price_gems' => 0,
                'color_primary' => '#64748b',
                'color_secondary' => '#eab308',
                'color_glow' => '#94a3b8',
                'bullet_color' => '#fef08a',
                'description' => 'Heavy industrial demolition armor built to withstand direct impacts and kinetic shock.',
                'stats' => ['speed' => 0.92, 'fire_rate' => 0.95, 'damage' => 1.12, 'max_hp' => 135, 'shield' => 60, 'bullet_speed' => 0.95, 'special_perk' => 'Shock Dampeners'],
                'is_default' => false,
            ],
            [
                'name' => 'Cyber Wasp',
                'slug' => 'cyber-wasp',
                'type' => 'scout',
                'rarity' => 'common',
                'price_coins' => 250,
                'price_gems' => 0,
                'color_primary' => '#fde047',
                'color_secondary' => '#18181b',
                'color_glow' => '#eab308',
                'bullet_color' => '#facc15',
                'description' => 'Ultra-light recon chassis designed for high agility harassment and rapid flanking.',
                'stats' => ['speed' => 1.15, 'fire_rate' => 1.05, 'damage' => 0.92, 'max_hp' => 85, 'shield' => 40, 'bullet_speed' => 1.1, 'special_perk' => 'Agile Thrusters'],
                'is_default' => false,
            ],
            [
                'name' => 'Aegis Sentinel',
                'slug' => 'aegis-sentinel',
                'type' => 'assault',
                'rarity' => 'common',
                'price_coins' => 300,
                'price_gems' => 0,
                'color_primary' => '#2563eb',
                'color_secondary' => '#f97316',
                'color_glow' => '#3b82f6',
                'bullet_color' => '#60a5fa',
                'description' => 'Tactical frontier security unit equipped with reinforced composite side plating.',
                'stats' => ['speed' => 1.02, 'fire_rate' => 1.0, 'damage' => 1.02, 'max_hp' => 105, 'shield' => 55, 'bullet_speed' => 1.02, 'special_perk' => 'Border Shield'],
                'is_default' => false,
            ],

            // --- RARE TIER ---
            [
                'name' => 'Toxic Viper',
                'slug' => 'toxic-viper',
                'type' => 'assault',
                'rarity' => 'rare',
                'price_coins' => 450,
                'price_gems' => 10,
                'color_primary' => '#10b981',
                'color_secondary' => '#84cc16',
                'color_glow' => '#22c55e',
                'bullet_color' => '#a3e635',
                'description' => 'Corrosive bio-reactive plating with high-velocity acid plasma cannons.',
                'stats' => ['speed' => 1.06, 'fire_rate' => 1.05, 'damage' => 1.08, 'max_hp' => 105, 'shield' => 50, 'bullet_speed' => 1.05, 'special_perk' => 'Acid Corrosive Tip'],
                'is_default' => false,
            ],
            [
                'name' => 'Cyber Phantom',
                'slug' => 'cyber-phantom',
                'type' => 'scout',
                'rarity' => 'rare',
                'price_coins' => 500,
                'price_gems' => 12,
                'color_primary' => '#a855f7',
                'color_secondary' => '#06b6d4',
                'color_glow' => '#c084fc',
                'bullet_color' => '#e879f9',
                'description' => 'Stealth-tuned reconnaissance speedster with low-signature electromagnetic dampeners.',
                'stats' => ['speed' => 1.18, 'fire_rate' => 1.08, 'damage' => 0.96, 'max_hp' => 90, 'shield' => 45, 'bullet_speed' => 1.12, 'special_perk' => 'Ghost Matrix'],
                'is_default' => false,
            ],
            [
                'name' => 'Venomous Hydra',
                'slug' => 'venomous-hydra',
                'type' => 'artillery',
                'rarity' => 'rare',
                'price_coins' => 550,
                'price_gems' => 15,
                'color_primary' => '#84cc16',
                'color_secondary' => '#15803d',
                'color_glow' => '#4ade80',
                'bullet_color' => '#bef264',
                'description' => 'Multi-chambered bio-toxin mortar platform delivering heavy splash kinetic strikes.',
                'stats' => ['speed' => 0.96, 'fire_rate' => 0.98, 'damage' => 1.18, 'max_hp' => 110, 'shield' => 50, 'bullet_speed' => 1.15, 'special_perk' => 'Toxic Payload'],
                'is_default' => false,
            ],
            [
                'name' => 'Vortex Stryker',
                'slug' => 'vortex-stryker',
                'type' => 'assault',
                'rarity' => 'rare',
                'price_coins' => 600,
                'price_gems' => 15,
                'color_primary' => '#0f766e',
                'color_secondary' => '#2dd4bf',
                'color_glow' => '#14b8a6',
                'bullet_color' => '#5eead4',
                'description' => 'Centrifugal ion turbine engine provides remarkable rotational torque and cannon stability.',
                'stats' => ['speed' => 1.08, 'fire_rate' => 1.1, 'damage' => 1.05, 'max_hp' => 105, 'shield' => 55, 'bullet_speed' => 1.08, 'special_perk' => 'Centrifugal Turbine'],
                'is_default' => false,
            ],
            [
                'name' => 'Goliath MK-IV',
                'slug' => 'goliath-mk-iv',
                'type' => 'heavy',
                'rarity' => 'rare',
                'price_coins' => 650,
                'price_gems' => 18,
                'color_primary' => '#4d7c0f',
                'color_secondary' => '#ca8a04',
                'color_glow' => '#65a30d',
                'bullet_color' => '#fef08a',
                'description' => 'Fourth generation armored siege chassis equipped with high-density kinetic ram bumper.',
                'stats' => ['speed' => 0.94, 'fire_rate' => 0.98, 'damage' => 1.16, 'max_hp' => 140, 'shield' => 65, 'bullet_speed' => 0.98, 'special_perk' => 'Titan Ram Armor'],
                'is_default' => false,
            ],
            [
                'name' => 'Tempest Lightning',
                'slug' => 'tempest-lightning',
                'type' => 'scout',
                'rarity' => 'rare',
                'price_coins' => 700,
                'price_gems' => 20,
                'color_primary' => '#eab308',
                'color_secondary' => '#06b6d4',
                'color_glow' => '#fde047',
                'bullet_color' => '#38bdf8',
                'description' => 'High-voltage capacitor rails discharge rapid electrical bursts across the grid.',
                'stats' => ['speed' => 1.2, 'fire_rate' => 1.12, 'damage' => 0.98, 'max_hp' => 90, 'shield' => 45, 'bullet_speed' => 1.2, 'special_perk' => 'Spark Discharge'],
                'is_default' => false,
            ],
            [
                'name' => 'Pulse Raptor',
                'slug' => 'pulse-raptor',
                'type' => 'scout',
                'rarity' => 'rare',
                'price_coins' => 750,
                'price_gems' => 22,
                'color_primary' => '#22c55e',
                'color_secondary' => '#6366f1',
                'color_glow' => '#4ade80',
                'bullet_color' => '#a7f3d0',
                'description' => 'Aerodynamic forward swept armor wings providing extreme cornering and evasive power.',
                'stats' => ['speed' => 1.22, 'fire_rate' => 1.14, 'damage' => 0.95, 'max_hp' => 88, 'shield' => 45, 'bullet_speed' => 1.18, 'special_perk' => 'Swept Wings'],
                'is_default' => false,
            ],

            // --- EPIC TIER ---
            [
                'name' => 'Plasma Void',
                'slug' => 'plasma-void',
                'type' => 'chrono',
                'rarity' => 'epic',
                'price_coins' => 900,
                'price_gems' => 30,
                'color_primary' => '#8b5cf6',
                'color_secondary' => '#ec4899',
                'color_glow' => '#a855f7',
                'bullet_color' => '#d946ef',
                'description' => 'Dark matter particle shielding and hyper-luminescent anti-gravity treads.',
                'stats' => ['speed' => 1.1, 'fire_rate' => 1.1, 'damage' => 1.14, 'max_hp' => 110, 'shield' => 70, 'bullet_speed' => 1.15, 'special_perk' => 'Dark Matter Shield'],
                'is_default' => false,
            ],
            [
                'name' => 'Frost Glitch',
                'slug' => 'frost-glitch',
                'type' => 'artillery',
                'rarity' => 'epic',
                'price_coins' => 950,
                'price_gems' => 32,
                'color_primary' => '#0284c7',
                'color_secondary' => '#38bdf8',
                'color_glow' => '#7dd3fc',
                'bullet_color' => '#bae6fd',
                'description' => 'Cryo-cooled superconducting barrel with sub-zero hyper-dense shell munitions.',
                'stats' => ['speed' => 1.08, 'fire_rate' => 1.12, 'damage' => 1.16, 'max_hp' => 108, 'shield' => 60, 'bullet_speed' => 1.22, 'special_perk' => 'Sub-Zero Freeze'],
                'is_default' => false,
            ],
            [
                'name' => 'Infernal Dreadnought',
                'slug' => 'infernal-dreadnought',
                'type' => 'heavy',
                'rarity' => 'epic',
                'price_coins' => 1050,
                'price_gems' => 35,
                'color_primary' => '#dc2626',
                'color_secondary' => '#f59e0b',
                'color_glow' => '#ef4444',
                'bullet_color' => '#fbbf24',
                'description' => 'Magma-cooled combustion reactor with blast-resistant ceramic undercarriage.',
                'stats' => ['speed' => 0.95, 'fire_rate' => 1.05, 'damage' => 1.22, 'max_hp' => 150, 'shield' => 70, 'bullet_speed' => 1.05, 'special_perk' => 'Thermal Burst'],
                'is_default' => false,
            ],
            [
                'name' => 'Shadow Specter',
                'slug' => 'shadow-specter',
                'type' => 'scout',
                'rarity' => 'epic',
                'price_coins' => 1100,
                'price_gems' => 38,
                'color_primary' => '#18181b',
                'color_secondary' => '#06b6d4',
                'color_glow' => '#22d3ee',
                'bullet_color' => '#67e8f9',
                'description' => 'Prismatic optical refraction skin bends arena laser rays, minimizing radar detection.',
                'stats' => ['speed' => 1.25, 'fire_rate' => 1.18, 'damage' => 1.04, 'max_hp' => 95, 'shield' => 50, 'bullet_speed' => 1.2, 'special_perk' => 'Optical Cloak'],
                'is_default' => false,
            ],
            [
                'name' => 'Neon Ronin',
                'slug' => 'neon-ronin',
                'type' => 'assault',
                'rarity' => 'epic',
                'price_coins' => 1200,
                'price_gems' => 40,
                'color_primary' => '#f43f5e',
                'color_secondary' => '#38bdf8',
                'color_glow' => '#fb7185',
                'bullet_color' => '#f472b6',
                'description' => 'Agile cyber-samurai chassis featuring calibrated stabilizer fins and rapid fire dual rails.',
                'stats' => ['speed' => 1.14, 'fire_rate' => 1.2, 'damage' => 1.12, 'max_hp' => 112, 'shield' => 60, 'bullet_speed' => 1.15, 'special_perk' => 'Katana Precision'],
                'is_default' => false,
            ],
            [
                'name' => 'Chrono Weaver',
                'slug' => 'chrono-weaver',
                'type' => 'chrono',
                'rarity' => 'epic',
                'price_coins' => 1300,
                'price_gems' => 45,
                'color_primary' => '#9333ea',
                'color_secondary' => '#e2e8f0',
                'color_glow' => '#c084fc',
                'bullet_color' => '#e9d5ff',
                'description' => 'Equipped with a micro-warp generator that accelerates energy replenishment and shield warp.',
                'stats' => ['speed' => 1.12, 'fire_rate' => 1.15, 'damage' => 1.15, 'max_hp' => 110, 'shield' => 75, 'bullet_speed' => 1.18, 'special_perk' => 'Warp Capacitor'],
                'is_default' => false,
            ],
            [
                'name' => 'Starlight Paladin',
                'slug' => 'starlight-paladin',
                'type' => 'assault',
                'rarity' => 'epic',
                'price_coins' => 1400,
                'price_gems' => 48,
                'color_primary' => '#f8fafc',
                'color_secondary' => '#3b82f6',
                'color_glow' => '#60a5fa',
                'bullet_color' => '#93c5fd',
                'description' => 'Crystalline photon armor disperses incoming kinetic strikes into ambient blue luminescence.',
                'stats' => ['speed' => 1.1, 'fire_rate' => 1.14, 'damage' => 1.14, 'max_hp' => 120, 'shield' => 70, 'bullet_speed' => 1.16, 'special_perk' => 'Photon Barrier'],
                'is_default' => false,
            ],
            [
                'name' => 'Rune Berserker',
                'slug' => 'rune-berserker',
                'type' => 'assault',
                'rarity' => 'epic',
                'price_coins' => 1450,
                'price_gems' => 50,
                'color_primary' => '#b91c1c',
                'color_secondary' => '#fbbf24',
                'color_glow' => '#f87171',
                'bullet_color' => '#fde047',
                'description' => 'Ancient runic telemetry combined with experimental overdrive thrusters for unrelenting aggression.',
                'stats' => ['speed' => 1.15, 'fire_rate' => 1.22, 'damage' => 1.18, 'max_hp' => 115, 'shield' => 55, 'bullet_speed' => 1.14, 'special_perk' => 'Berserk Overclock'],
                'is_default' => false,
            ],
            [
                'name' => 'Dark Nebula',
                'slug' => 'dark-nebula',
                'type' => 'chrono',
                'rarity' => 'epic',
                'price_coins' => 1500,
                'price_gems' => 52,
                'color_primary' => '#581c87',
                'color_secondary' => '#f43f5e',
                'color_glow' => '#9333ea',
                'bullet_color' => '#f472b6',
                'description' => 'Absorbs electromagnetic arena radiation to fuel an ominous deep purple photon cannon.',
                'stats' => ['speed' => 1.12, 'fire_rate' => 1.16, 'damage' => 1.16, 'max_hp' => 114, 'shield' => 72, 'bullet_speed' => 1.18, 'special_perk' => 'Cosmic Siphon'],
                'is_default' => false,
            ],

            // --- LEGENDARY TIER ---
            [
                'name' => 'Crimson Titan',
                'slug' => 'crimson-titan',
                'type' => 'heavy',
                'rarity' => 'legendary',
                'price_coins' => 1800,
                'price_gems' => 65,
                'color_primary' => '#ef4444',
                'color_secondary' => '#f59e0b',
                'color_glow' => '#ff2200',
                'bullet_color' => '#fbbf24',
                'description' => 'Reinforced tungsten titanium alloy chassis engineered for absolute arena supremacy.',
                'stats' => ['speed' => 1.02, 'fire_rate' => 1.15, 'damage' => 1.28, 'max_hp' => 165, 'shield' => 80, 'bullet_speed' => 1.15, 'special_perk' => 'Tungsten Aegis'],
                'is_default' => false,
            ],
            [
                'name' => 'Solaris Gold',
                'slug' => 'solaris-gold',
                'type' => 'assault',
                'rarity' => 'legendary',
                'price_coins' => 2000,
                'price_gems' => 75,
                'color_primary' => '#eab308',
                'color_secondary' => '#ea580c',
                'color_glow' => '#fde047',
                'bullet_color' => '#fef08a',
                'description' => 'Mastercraft 24k gilded finish radiating high-energy solar corona heatwaves.',
                'stats' => ['speed' => 1.18, 'fire_rate' => 1.2, 'damage' => 1.24, 'max_hp' => 130, 'shield' => 75, 'bullet_speed' => 1.22, 'special_perk' => 'Corona Blast'],
                'is_default' => false,
            ],
            [
                'name' => 'Obsidian Colossus',
                'slug' => 'obsidian-colossus',
                'type' => 'heavy',
                'rarity' => 'legendary',
                'price_coins' => 2200,
                'price_gems' => 80,
                'color_primary' => '#18181b',
                'color_secondary' => '#f97316',
                'color_glow' => '#ea580c',
                'bullet_color' => '#fb923c',
                'description' => 'Volcanic obsidian composite plating with superheated plasma discharge bores.',
                'stats' => ['speed' => 1.0, 'fire_rate' => 1.14, 'damage' => 1.32, 'max_hp' => 170, 'shield' => 85, 'bullet_speed' => 1.12, 'special_perk' => 'Magma Core'],
                'is_default' => false,
            ],
            [
                'name' => 'Hyperion Rail',
                'slug' => 'hyperion-rail',
                'type' => 'artillery',
                'rarity' => 'legendary',
                'price_coins' => 2400,
                'price_gems' => 85,
                'color_primary' => '#2563eb',
                'color_secondary' => '#e0e7ff',
                'color_glow' => '#3b82f6',
                'bullet_color' => '#60a5fa',
                'description' => 'Ultra-long range electromagnetic mass driver accelerates hyper-dense tungsten darts.',
                'stats' => ['speed' => 1.08, 'fire_rate' => 1.15, 'damage' => 1.35, 'max_hp' => 125, 'shield' => 65, 'bullet_speed' => 1.35, 'special_perk' => 'Rail Piercer'],
                'is_default' => false,
            ],
            [
                'name' => 'Nova Devastator',
                'slug' => 'nova-devastator',
                'type' => 'artillery',
                'rarity' => 'legendary',
                'price_coins' => 2600,
                'price_gems' => 90,
                'color_primary' => '#ea580c',
                'color_secondary' => '#8b5cf6',
                'color_glow' => '#f97316',
                'bullet_color' => '#c084fc',
                'description' => 'Thermonuclear plasma battery generates explosive spherical fusion impacts.',
                'stats' => ['speed' => 1.06, 'fire_rate' => 1.18, 'damage' => 1.34, 'max_hp' => 130, 'shield' => 70, 'bullet_speed' => 1.25, 'special_perk' => 'Thermonuclear Shock'],
                'is_default' => false,
            ],
            [
                'name' => 'Abyssal Leviathan',
                'slug' => 'abyssal-leviathan',
                'type' => 'heavy',
                'rarity' => 'legendary',
                'price_coins' => 2800,
                'price_gems' => 95,
                'color_primary' => '#1e3a8a',
                'color_secondary' => '#06b6d4',
                'color_glow' => '#0284c7',
                'bullet_color' => '#38bdf8',
                'description' => 'Deep ocean pressure alloy with bio-luminescent warning pulses and heavy hydraulic dampening.',
                'stats' => ['speed' => 1.04, 'fire_rate' => 1.16, 'damage' => 1.3, 'max_hp' => 160, 'shield' => 90, 'bullet_speed' => 1.18, 'special_perk' => 'Hydro-Armor'],
                'is_default' => false,
            ],
            [
                'name' => 'Zero Kelvin',
                'slug' => 'zero-kelvin',
                'type' => 'artillery',
                'rarity' => 'legendary',
                'price_coins' => 3000,
                'price_gems' => 100,
                'color_primary' => '#06b6d4',
                'color_secondary' => '#f0fdf4',
                'color_glow' => '#67e8f9',
                'bullet_color' => '#a5f3fc',
                'description' => 'Absolute-zero cryogenic rail shoots super-cooled solid ice-plasma crystals.',
                'stats' => ['speed' => 1.12, 'fire_rate' => 1.22, 'damage' => 1.28, 'max_hp' => 125, 'shield' => 80, 'bullet_speed' => 1.3, 'special_perk' => 'Absolute Zero'],
                'is_default' => false,
            ],
            [
                'name' => 'Valkyrie Prime',
                'slug' => 'valkyrie-prime',
                'type' => 'assault',
                'rarity' => 'legendary',
                'price_coins' => 3200,
                'price_gems' => 110,
                'color_primary' => '#ffffff',
                'color_secondary' => '#eab308',
                'color_glow' => '#fef08a',
                'bullet_color' => '#fde047',
                'description' => 'The crown jewel of championship combat. Pristine white chassis with gilded gold accents.',
                'stats' => ['speed' => 1.22, 'fire_rate' => 1.25, 'damage' => 1.26, 'max_hp' => 135, 'shield' => 85, 'bullet_speed' => 1.25, 'special_perk' => 'Prime Divinity'],
                'is_default' => false,
            ],

            // --- MYTHIC TIER (GOD-TIER PROTOTYPES) ---
            [
                'name' => 'Apex Overlord',
                'slug' => 'apex-overlord',
                'type' => 'destroyer',
                'rarity' => 'mythic',
                'price_coins' => 4500,
                'price_gems' => 150,
                'color_primary' => '#f43f5e',
                'color_secondary' => '#fb7185',
                'color_glow' => '#e11d48',
                'bullet_color' => '#fda4af',
                'description' => 'Classified military prototype utilizing dual tachyon accelerators and anti-matter matrix.',
                'stats' => ['speed' => 1.25, 'fire_rate' => 1.3, 'damage' => 1.4, 'max_hp' => 145, 'shield' => 95, 'bullet_speed' => 1.32, 'special_perk' => 'Tachyon Overdrive'],
                'is_default' => false,
            ],
            [
                'name' => 'Quantum Singularity',
                'slug' => 'quantum-singularity',
                'type' => 'chrono',
                'rarity' => 'mythic',
                'price_coins' => 5000,
                'price_gems' => 180,
                'color_primary' => '#6366f1',
                'color_secondary' => '#38bdf8',
                'color_glow' => '#818cf8',
                'bullet_color' => '#c7d2fe',
                'description' => 'Contains a contained miniature singularity powering relativistic kinetic discharges.',
                'stats' => ['speed' => 1.24, 'fire_rate' => 1.32, 'damage' => 1.38, 'max_hp' => 140, 'shield' => 105, 'bullet_speed' => 1.35, 'special_perk' => 'Graviton Well'],
                'is_default' => false,
            ],
            [
                'name' => 'Omega Punisher',
                'slug' => 'omega-punisher',
                'type' => 'destroyer',
                'rarity' => 'mythic',
                'price_coins' => 5500,
                'price_gems' => 200,
                'color_primary' => '#991b1b',
                'color_secondary' => '#0f172a',
                'color_glow' => '#dc2626',
                'bullet_color' => '#f87171',
                'description' => 'Forged in black ops laboratories to eradicate entire bot swarms with one synchronized barrage.',
                'stats' => ['speed' => 1.15, 'fire_rate' => 1.35, 'damage' => 1.45, 'max_hp' => 160, 'shield' => 90, 'bullet_speed' => 1.28, 'special_perk' => 'Omega Annihilation'],
                'is_default' => false,
            ],
            [
                'name' => 'Cyberpunk Zero',
                'slug' => 'cyberpunk-zero',
                'type' => 'destroyer',
                'rarity' => 'mythic',
                'price_coins' => 6000,
                'price_gems' => 220,
                'color_primary' => '#00ff66',
                'color_secondary' => '#ff0055',
                'color_glow' => '#00ffaa',
                'bullet_color' => '#ff007f',
                'description' => 'The ultimate hacker war-machine. Glitches reality with matrix code aura and hyper-pulse fire.',
                'stats' => ['speed' => 1.3, 'fire_rate' => 1.38, 'damage' => 1.42, 'max_hp' => 150, 'shield' => 100, 'bullet_speed' => 1.4, 'special_perk' => 'Reality Glitch Matrix'],
                'is_default' => false,
            ],
        ];

        $createdSkins = [];
        foreach ($skins as $skinData) {
            $createdSkins[] = Skin::updateOrCreate(
                ['slug' => $skinData['slug']],
                $skinData
            );
        }

        // 2. Create Commander User
        $commander = User::where('email', 'commander@blitzgrid.io')
            ->orWhere('username', 'CommanderAlex')
            ->first();

        $commanderData = [
            'name' => 'Commander Alex',
            'surname' => 'Vance',
            'username' => 'CommanderAlex',
            'email' => 'commander@blitzgrid.io',
            'password' => Hash::make('password123'),
            'phone' => '+15550192834',
            'date_of_birth' => '1996-05-14',
            'street_address' => '742 Evergreen Cyber Way, Suite 402',
            'city' => 'Neo Seattle',
            'country' => 'United States',
            'post_code' => '98101',
            'terms_accepted_at' => now(),
            'coins' => 2400,
            'gems' => 150,
            'kills_total' => 64,
            'deaths_total' => 14,
            'matches_played' => 18,
        ];

        if ($commander) {
            $commander->update($commanderData);
        } else {
            $commander = User::create($commanderData);
        }

        // Equip default skin (Neon Vanguard) at Level 3 and attach Frost Glitch at Level 2, Iron Behemoth at Level 1
        $commander->skins()->syncWithoutDetaching([
            $createdSkins[0]->id => ['is_equipped' => true, 'level' => 3],
            $createdSkins[4]->id => ['is_equipped' => false, 'level' => 2],
            $createdSkins[1]->id => ['is_equipped' => false, 'level' => 1],
        ]);

        // 3. Create Leaderboard rivals
        $rivals = [
            ['name' => 'Travis Drake', 'username' => 'CyberStriker', 'email' => 'cyberstriker@blitzgrid.io', 'coins' => 5400, 'gems' => 220, 'kills' => 184, 'deaths' => 38, 'matches' => 45, 'skin_idx' => 31],
            ['name' => 'Jin Kazama', 'username' => 'NeonGhost', 'email' => 'neonghost@blitzgrid.io', 'coins' => 4800, 'gems' => 195, 'kills' => 142, 'deaths' => 41, 'matches' => 39, 'skin_idx' => 29],
            ['name' => 'Astrid Lind', 'username' => 'Valkyrie99', 'email' => 'valkyrie99@blitzgrid.io', 'coins' => 3900, 'gems' => 160, 'kills' => 118, 'deaths' => 29, 'matches' => 30, 'skin_idx' => 27],
            ['name' => 'Eero Virtanen', 'username' => 'QuantumTank', 'email' => 'quantumtank@blitzgrid.io', 'coins' => 2950, 'gems' => 110, 'kills' => 96, 'deaths' => 33, 'matches' => 28, 'skin_idx' => 28],
            ['name' => 'Chloe Bennett', 'username' => 'ApexGunner', 'email' => 'apexgunner@blitzgrid.io', 'coins' => 2450, 'gems' => 80, 'kills' => 75, 'deaths' => 20, 'matches' => 22, 'skin_idx' => 23],
        ];

        foreach ($rivals as $rival) {
            $skinIdx = $rival['skin_idx'] ?? 0;
            $user = User::where('username', $rival['username'])
                ->orWhere('email', $rival['email'])
                ->first();

            $userData = [
                'name' => $rival['name'],
                'surname' => 'Rival',
                'username' => $rival['username'],
                'email' => $rival['email'],
                'password' => Hash::make('password123'),
                'coins' => $rival['coins'],
                'gems' => $rival['gems'],
                'kills_total' => $rival['kills'],
                'deaths_total' => $rival['deaths'],
                'matches_played' => $rival['matches'],
                'street_address' => '101 Cyber Plaza',
                'city' => 'Night City',
                'country' => 'United States',
                'post_code' => '90001',
                'terms_accepted_at' => now(),
            ];

            if ($user) {
                $user->update($userData);
            } else {
                $user = User::create($userData);
            }

            $user->skins()->syncWithoutDetaching([
                $createdSkins[$skinIdx]->id => ['is_equipped' => true, 'level' => rand(3, 7)]
            ]);

            // Create sample match logs if none exist for this user
            if (GameMatch::where('user_id', $user->id)->count() === 0) {
                GameMatch::create([
                    'user_id' => $user->id,
                    'player_name' => $user->name,
                    'kills' => rand(6, 15),
                    'deaths' => rand(0, 3),
                    'damage_dealt' => rand(1200, 3400),
                    'score' => rand(2500, 6800),
                    'coins_earned' => rand(180, 450),
                    'gems_earned' => rand(3, 12),
                    'duration_seconds' => rand(150, 420),
                    'game_mode' => 'free_for_all',
                ]);
            }
        }

        // Commander's recent matches
        if (GameMatch::where('user_id', $commander->id)->count() === 0) {
            GameMatch::create([
                'user_id' => $commander->id,
                'player_name' => $commander->name,
                'kills' => 9,
                'deaths' => 1,
                'damage_dealt' => 1850,
                'score' => 3700,
                'coins_earned' => 280,
                'gems_earned' => 8,
                'duration_seconds' => 210,
                'game_mode' => 'free_for_all',
            ]);
        }
    }
}

